name: "Fuzz: graymatter"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/graymatter-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: graymatter
      docker_image: 'ghcr.io/jambrains/graymatter/gm:conformance-fuzzer-latest'
      docker_cmd: 'fuzz-m1-target --stay-open --listen {TARGET_SOCK}'
      mention: franciscoaguirre
