name: "Demo (full): graymatter"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/graymatter-demo-full.yml'
      - '.github/workflows/demo-source.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: graymatter
      docker_image: 'ghcr.io/jambrains/graymatter/gm:conformance-fuzzer-latest'
      spec: full
      num_blocks: 500
      mention: franciscoaguirre
