name: "Performance: jam4s"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-picofuzz.yml
    with:
      target_name: jam4s
      docker_image: 'jamforscala/jam4s:0.7.2-rc.11-amd64'
      docker_cmd: '--fuzz --seed 0 --socket {TARGET_SOCK}'
      docker_env: 'CONFIG_FILE=app/config/node-dev.conf'
