name: "Fuzz: jam4s"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jam4s-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jam4s
      docker_image: 'jamforscala/jam4s:0.7.2-rc.11-amd64'
      docker_cmd: '--fuzz --seed 0 --socket {TARGET_SOCK}'
      docker_env: 'CONFIG_FILE=app/config/node-dev.conf'
      docker_memory: '4096m'
      mention: celadari
