name: "Demo (full): jam4s"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jam4s-demo-full.yml'
      - '.github/workflows/demo-source.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jam4s
      docker_image: 'jamforscala/jam4s:latest'
      docker_memory: '4096m'
      spec: full
      num_blocks: 500
      mention: celadari
