name: "Fuzz: jambda"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jambda-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jambda
      docker_image: 'ghcr.io/archelabs/jambda-fuzz-target:latest'
      mention: libingjiang47
