name: "Fuzz: jamforge"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jamforge-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jamforge
      docker_image: 'ghcr.io/philoniare/jam-forge:latest'
      docker_cmd: '--socket-path {TARGET_SOCK}'
      docker_memory: '4096m'
      mention: philoniare
