name: "Fuzz: jampy-recompiler"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jampy-recompiler-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jampy-recompiler
      docker_image: 'ghcr.io/dakk/jampy-target:0.7.2'
      docker_cmd: '--use-recompiler --sock {TARGET_SOCK}'
      mention: dakk
