name: "Demo (full): jampy-recompiler"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jampy-recompiler-demo-full.yml'
      - '.github/workflows/demo-source.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jampy-recompiler
      docker_image: 'ghcr.io/dakk/jampy-target:0.7.2'
      spec: full
      num_blocks: 500
      mention: dakk
