name: "Performance: jamzilla-int"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-picofuzz.yml
    with:
      target_name: jamzilla-int
      docker_image: 'ghcr.io/ascrivener/jamzilla-tiny:edge'
      docker_cmd: '-socket {TARGET_SOCK}'
      docker_env: 'PVM_MODE=interpreter'
