name: "Demo (tiny): jamzilla-int"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jamzilla-int-demo-tiny.yml'
      - '.github/workflows/demo-source.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jamzilla-int
      docker_image: 'ghcr.io/ascrivener/jamzilla:edge'
      docker_cmd: '-socket {TARGET_SOCK}'
      docker_env: 'PVM_MODE=interpreter'
      spec: tiny
      mention: ascrivener
