name: "Demo (tiny): javajam"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/javajam-demo-tiny.yml'
      - '.github/workflows/demo-source.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: javajam
      docker_image: 'ghcr.io/methodfive/javajam:latest-amd64'
      docker_cmd: '-Dskip.warmup=true fuzz {TARGET_SOCK}'
      docker_memory: '8192m'
      spec: tiny
      mention: jaymansfield
