name: "Fuzz: jotl"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jotl-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: jotl
      docker_image: 'ghcr.io/polykrate/jotl:latest'
      docker_cmd: '{TARGET_SOCK}'
      docker_memory: '2048m'
      readiness_pattern: 'Listening on'
      mention: polykrate
