name: "Performance: jotl"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jotl-performance.yml'

jobs:
  test:
    uses: ./.github/workflows/reusable-picofuzz.yml
    with:
      target_name: jotl
      docker_image: 'ghcr.io/polykrate/jotl:latest'
      docker_memory: '2048m'
      readiness_pattern: 'Listening on'
