name: "Fuzz: new-jamneration"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/new-jamneration-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: new-jamneration
      docker_image: 'ghcr.io/new-jamneration/new-jamneration-target:latest'
      docker_cmd: '{TARGET_SOCK}'
      docker_env: 'USE_MINI_REDIS=true'
      mention: YCC3741
