name: "Fuzz: pbnjam"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/pbnjam-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: pbnjam
      docker_image: 'shimonchick/pbnjam-fuzzer-target:latest'
      docker_cmd: '--socket {TARGET_SOCK}'
      docker_memory: '4096m'
      mention: mikirov
