name: "Performance: pbnjam"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/pbnjam-performance.yml'

jobs:
  test:
    uses: ./.github/workflows/reusable-picofuzz.yml
    with:
      target_name: pbnjam
      docker_image: 'shimonchick/pbnjam-fuzzer-target:latest'
      docker_cmd: '--socket {TARGET_SOCK}'
      docker_memory: '4096m'
