name: "Demo (full): turbojam"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/turbojam-demo-full.yml'
      - '.github/workflows/demo-source.yml'

permissions:
  contents: read
  issues: write

jobs:
  demo:
    uses: ./.github/workflows/demo-source.yml
    with:
      target_name: turbojam
      docker_image: 'r2rationality/turbojam-fuzz:latest'
      docker_memory: '8192m'
      spec: full
      num_blocks: 500
      mention: sierkov
