name: "Fuzz: turbojam"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/turbojam-fuzz.yml'

permissions:
  contents: read
  issues: write

jobs:
  graymatter-source:
    strategy:
      fail-fast: false
      matrix:
        include:
          - spec: tiny
            num_blocks: 175000
          - spec: full
            num_blocks: 17500
    uses: ./.github/workflows/graymatter-fuzz-source.yml
    with:
      target_name: turbojam
      docker_image: 'r2rationality/turbojam-fuzz:latest'
      docker_cmd: ${{ fromJson('{"tiny":"fuzzer-api {TARGET_SOCK}","full":""}')[matrix.spec] }}
      spec: ${{ matrix.spec }}
      timeout_minutes: 1380
      num_blocks: ${{ matrix.num_blocks }}
      num_runs: 10
      mention: sierkov
