name: "Performance: typeberry"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    # we want to run typeberry on each and every PR just as a sanity check
    # paths:
    #   - '.github/workflows/typeberry-performance.yml'

jobs:
  test:
    uses: ./.github/workflows/reusable-picofuzz.yml
    with:
      target_name: typeberry
      docker_image: 'ghcr.io/fluffylabs/typeberry:latest'
      docker_cmd: ''
      docker_env: 'JAM_LOG=log'
      readiness_pattern: 'PVM Backend'
