name: "Performance: vinwolf"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/vinwolf-performance.yml'

jobs:
  test:
    uses: ./.github/workflows/reusable-picofuzz.yml
    with:
      target_name: vinwolf
      docker_image: 'ghcr.io/bloppan/vinwolf-target:latest'
      readiness_pattern: 'listening on'
